### ISSUE TITLE
Can't run this

### ISSUE THREAD

**Issue by csterritt** [taylorhughes/skit-react#1]
Hi -- new to Skit, know a fair amount about React.

I'm trying the following commands to run the project:

```
npm install skit
npm install
```

Then

```
./node_modules/.bin/skit run root --debug
```

But what happens is I get the following output:

```
[skit] loading module tree
/Volumes/Second/Chris/hacks/skit/skit-react/node_modules/skit/lib/loader/loader.js:103
      throw e;
            ^
Error: Invalid resource -- could not identify wrapper: /Volumes/Second/Chris/hacks/skit/skit-react/root/library/BaseController.jsx
    at SkitModule.addFile (/Volumes/Second/Chris/hacks/skit/skit-react/node_modules/skit/lib/loader/SkitModule.js:62:15)
    at /Volumes/Second/Chris/hacks/skit/skit-react/node_modules/skit/lib/loader/loader.js:100:18
    at Array.forEach (native)
    at Object.buildModuleTree (/Volumes/Second/Chris/hacks/skit/skit-react/node_modules/skit/lib/loader/loader.js:65:9)
    at BundledLoader.load_ (/Volumes/Second/Chris/hacks/skit/skit-react/node_modules/skit/lib/loader/BundledLoader.js:130:21)
    at new BundledLoader (/Volumes/Second/Chris/hacks/skit/skit-react/node_modules/skit/lib/loader/BundledLoader.js:119:8)
    at new SkitServer (/Volumes/Second/Chris/hacks/skit/skit-react/node_modules/skit/lib/SkitServer.js:62:17)
    at command_run (/Volumes/Second/Chris/hacks/skit/skit-react/node_modules/skit/bin/skit:140:16)
    at main (/Volumes/Second/Chris/hacks/skit/skit-react/node_modules/skit/bin/skit:242:7)
    at Object.<anonymous> (/Volumes/Second/Chris/hacks/skit/skit-react/node_modules/skit/bin/skit:264:1)
```

Help!  Thanks!

**Comment by taylorhughes** [comment]
Sorry about that, I should provide instructions. Because of the non-standard resource wrapper (defined in main.js) you have to run main.js — eg. <code>node main.js</code> — rather than using <code>skit run</code>

**Comment by taylorhughes** [comment]
updated README with instructions

**Comment by csterritt** [comment]
Thanks for the fix!
